#!/usr/bin/python
# CUMULUS-AUTOPROVISIONING

# Copyright (C) 2019 Cumulus Networks, Inc. All rights reserved
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# https://www.debian.org/legal/licenses/mit
#

import logging
import logging.handlers
import subprocess
import os
import json
import time
import socket
import sys

VX = False
USERNAME = None
PASSWORD = None
CLUSTER_IP = None
MANAGEMENT_IP = None
UPLINKS = None
GATEWAY = None
PEERLINK = "swp49,swp50"
ZTP = None
BRIDGE_IP = None

log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)
handler = logging.handlers.SysLogHandler(address='/dev/log')
formatter = logging.Formatter(
    "Nutanix ZTP[%(process)d]: %(message)s", None)
handler.setFormatter(formatter)
log.addHandler(handler)


def check_license():
    '''
    Check if the switch is licensed
    '''
    # cl-license returns 0 if the license is installed
    return subprocess.Popen(["cl-license"], stdout=subprocess.PIPE).returncode == 0


def install_license():
    '''
    install a Cumulus license
    '''
    log.info("Installing Cumulus Linux license")

    if check_license():
        log.info(
            "Error installing license, please check that the license.txt file is valid")
        exit(1)

    try:
        file = open("/etc/cumulus/.license", "w+")
    except IOError:
        log.info(
            "Unable to open license file /etc/cumulus/.license. Exiting")
        exit(1)

    file.write("LICENSE_KEY_GOES_HERE")
    file.close()

    subprocess.Popen(["systemctl", "reset-failed",
                      "switchd.service"], stdout=subprocess.PIPE)
    subprocess.Popen(
        ["systemctl", "restart", "switchd.service"], stdout=subprocess.PIPE)

    timer = 0
    while timer < 120:

        proc = subprocess.Popen(["systemctl", "show",
                                 "switchd.service",
                                 "--no-page"],
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        (output, err) = proc.communicate()

        for line in output.split("\n"):
            if line.split("=")[0] == "ActiveState":
                if line.split("=")[1] == "active":
                    return

        timer += 1
        time.sleep(1)

    log.info("Unable to start switchd after applying a license."
                 "Please view \"journalctl -u switchd.service\""
                 "for more information. Exiting.")
    exit(1)


def check_nclu_ready():
    '''
    Check if NCLU and netd are ready
    '''
    log.info("Checking for NCLU")
    return subprocess.Popen(["net", "show", "interface"], stdout=subprocess.PIPE).returncode == 0


def get_interfaces():
    '''
    Get a json list of the interfaces. Expects NCLU to be running
    '''
    proc = subprocess.Popen(["net", "show", "interface", "json"],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, err) = proc.communicate()

    if proc.returncode != 0:
        log.info("Problem fetching interfaces. Maybe an issue with NCLU? %s", err)
        exit(1)

    return json.loads(output)


def set_swp_mtu(interfaces):
    '''
    Set the MTU of all swp ports on the box to 9000
    '''
    log.info("Enabling front panel ports")
    interface_line = []

    for interface in interfaces.keys():
        if interface[:3] == "swp":
            interface_line.append(interface)

    proc = subprocess.Popen(["net", "add", "interface", ",".join(
        interface_line), "mtu", "9000"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    err = proc.communicate()[1]

    if proc.returncode == 0:
        return True
    else:
        log.info("Encounter an error setting MTU. %s", err)
        exit(1)


def enable_mgmt_vrf():
    '''
    Enable management VRF and set the MANAGEMENT_IP if defined
    '''
    log.info("Configuring eth0 interface")
    proc = subprocess.Popen(["net", "add", "vrf", "mgmt"],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    proc.wait()
    (output, err) = proc.communicate()

    if proc.returncode != 0:
        log.info("Encountered an error configuring management VRF. %s", str(err))
        exit(1)

    if MANAGEMENT_IP:
        proc = subprocess.Popen(["net", "add", "interface", "eth0", "ip", "address",
                                 MANAGEMENT_IP], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        proc.wait()
        (output, err) = proc.communicate()
        if proc.returncode != 0:
            log.info("Encountered an error assigning IP address"
                     "%s to eth0. %s", MANAGEMENT_IP, str(err))
            exit(1)

        if GATEWAY:
            proc = subprocess.Popen(["net", "add", "routing", "route", "0.0.0.0/0",
                                     GATEWAY, "vrf", "mgmt"],
                                    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            (output, err) = proc.communicate()
            proc.wait()
            if proc.returncode != 0:
                log.info("Encountered an error assigning the default gateway %s"
                         "to the management interface. %s", GATEWAY, str(output))
                exit(1)


def load_config():
    '''
    Load the ZTP configuration file to define paramaters
    '''
    log.info("Loading Nutanix ztp_config.txt file")
    global USERNAME
    global PASSWORD
    global CLUSTER_IP
    global MANAGEMENT_IP
    global UPLINKS
    global GATEWAY
    global PEERLINK
    global BRIDGE_IP
    error = False

    try:
        file = open(ZTP + "/ztp_config.txt")
    except IOError:
        log.info("Unable to open ztp_config.txt file. Exiting")
        exit(1)

    with file:
        for line in file:
            split = line.strip().split("=")
            if len(split) <= 1:
                continue
            key = split[0].upper()
            value = split[1]
            if key == "NUTANIX_USERNAME":
                USERNAME = value
            if key == "NUTANIX_PASSWORD":
                PASSWORD = value
            if key == "NUTANIX_IP":
                CLUSTER_IP = value
            if key == "SWITCH_MANAGEMENT_IP":
                MANAGEMENT_IP = value
            if key == "UPLINKS":
                UPLINKS = value
            if key == "SWITCH_DEFAULT_GATEWAY":
                GATEWAY = value
            if key == "PEERLINK":
                PEERLINK = value
            if key == "SWITCH_CVM_IP":
                BRIDGE_IP = value

    if not USERNAME:
        error = "NUTANIX_USERNAME"
    if not PASSWORD:
        error = "NUTANIX_PASSWORD"
    if not CLUSTER_IP:
        error = "NUTANIX_IP"
    if not BRIDGE_IP:
        error = "SWITCH_CVM_IP"

    if error:
        log.info("%s not defined in the ztp_config.txt file. Exiting", error)
        exit(1)

    try:
        socket.inet_aton(CLUSTER_IP)
    except socket.error:
        log.info("Invalid NUTANIX_IP. Exiting")
        exit(1)

    return True


def build_nutanix_config():
    '''
    Produce the cumulus-hyperconverged configuration file
    '''
    log.info("Generating /etc/default/cumulus-hyperconverged file")
    output_lines = []
    output_lines.append("### /etc/default/cumulus-hyperconverged config file")
    output_lines.append("# username for Prism (required)")
    output_lines.append("USERNAME=" + USERNAME)
    output_lines.append("# password for Prism (required)")
    output_lines.append("PASSWORD=" + PASSWORD)
    output_lines.append("# CVM address used by the service (required)")
    output_lines.append("SERVER=" + CLUSTER_IP)
    output_lines.append("# single/multi rack configuration (optional)")
    output_lines.append("VXLAN_CONFIG=False")
    output_lines.append("")

    try:
        file = open("/etc/default/cumulus-hyperconverged", "w+")
    except IOError:
        log.info(
            "Unable to open Cumulus HCS file /etc/default/cumulus-hyperconverged. Exiting")
        exit(1)

    file.write("\n".join(output_lines))
    file.close()


def configure_uplinks():
    """
    Put all of the uplinks in the bridge
    Assign all VLANs to the bridge
    """
    log.info("Configuring uplink interfaces")
    for interface in UPLINKS.split(","):
        if interface[:3] != "swp":
            log.info("Invalid interface in UPLINK list. Exiting")
            exit(1)

    proc = subprocess.Popen(["net", "add", "bridge", "bridge", "ports",
                             UPLINKS], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    proc.wait()
    (output, err) = proc.communicate()

    if proc.returncode != 0:
        log.info("Encountered an error placing uplink interfaces %s into a bridge. %s",
                 UPLINKS, err)
        exit(1)

    proc = subprocess.Popen(["net", "add", "bridge", "bridge", "vids",
                             "1-2999"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    proc.wait()
    (output, err) = proc.communicate()

    if proc.returncode != 0:
        log.info("Encountered an error adding VLANs 1-2999. %s",
                 err)
        exit(1)

    proc = subprocess.Popen(["net", "add", "bridge", "bridge", "vids",
                             "4000-4094"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    proc.wait()
    (output, err) = proc.communicate()

    if proc.returncode != 0:
        log.info("Encountered an error adding VLANs 4000-4095. %s",
                 err)
        exit(1)


def enable_hyperconverged_service():
    '''
    Start the cumulus-hyperconverged service at boot time
    and start it right now
    '''
    log.info("Enabling cumulus-hyperconverged service")
    subprocess.Popen(["systemctl", "enable", "cumulus-hyperconverged.service"],
                     stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    proc = subprocess.Popen(["systemctl", "start", "cumulus-hyperconverged.service"],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    timer = 0
    while timer < 30:

        proc = subprocess.Popen(["systemctl", "show",
                                 "cumulus-hyperconverged.service",
                                 "--no-page"],
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        (output, err) = proc.communicate()

        for line in output.split("\n"):
            if line.split("=")[0] == "ActiveState":
                if line.split("=")[1] == "active":
                    return

        timer += 1
        time.sleep(1)

    log.info("Unable to start cumulus-hyperconverged service."
             "Please check \"journalctl -u "
             "cumulus-hyperconverged.service\""
             "for more information. Exiting.")

    exit(1)

def enable_clag():
    '''
    Enable CLAG on the defined PEERLINK ports.
    The default ports are swp49 and swp50.
    If the ports provided do not exist on the switch
    (or if the switch doesn't have a swp49 or swp50)
    ifreload -a will fail and the ZTP script will produce an error and exit
    '''
    log.info("Enabling MLAG")
    peerlink_bond = " ".join(PEERLINK.split(","))
    clag_lines = [""]
    clag_lines.append("auto peerlink")
    clag_lines.append("iface peerlink")
    clag_lines.append("  bond-slaves " + peerlink_bond)
    clag_lines.append("")
    clag_lines.append("auto peerlink.4094")
    clag_lines.append("iface peerlink.4094")
    clag_lines.append("   clagd-peer-ip linklocal")
    clag_lines.append("   clagd-sys-mac 44:38:39:FF:40:00")
    clag_lines.append("")
    clag_lines.append("auto bridge")
    clag_lines.append("iface bridge")
    clag_lines.append("    bridge-ports peerlink")
    clag_lines.append("    bridge-vids 1")
    clag_lines.append("    bridge-vlan-aware yes")
    clag_lines.append("")
    clag_lines.append("auto vlan1")
    clag_lines.append("iface vlan1")
    clag_lines.append("    address " + BRIDGE_IP)
    clag_lines.append("    vlan-id 1")
    clag_lines.append("    vlan-raw-device bridge")
    clag_lines.append("")

    try:
        file = open("/etc/network/interfaces", "a+")
    except IOError:
        log.info("Unable to open /etc/network/interfaces file. Exiting")
        exit(1)

    file.write("\n".join(clag_lines))
    file.close()

    proc = subprocess.Popen(
        ["ifreload", "-a"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    # Wait for ifreload to complete otherwise we will move on without a return code
    proc.wait()

    if proc.returncode != 0:
        log.info("Unable to apply peerlink or bridge interface configuration, "
                 "verify that the peerlink ports exist or bridge IP is correct."
                 "Exiting. %s",
                 proc.communicate()[1])
        exit(1)


def place_ntp_in_vrf():
    '''
    Move NTP to the management VRF
    '''
    log.info("Configuring NTP")
    subprocess.Popen(["systemctl", "stop", "ntp.service"],
                     stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    subprocess.Popen(["systemctl", "disable", "ntp.service"],
                     stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    subprocess.Popen(["systemctl", "start", "ntp@mgmt.service"],
                     stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    subprocess.Popen(["systemctl", "enable", "ntp@mgmt.service"],
                     stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def apply_nclu_config():
    '''
    Run "net commit"
    '''
    log.info("Applying configuration")

    proc = subprocess.Popen(["net", "pending"],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    log.info("Pending config: %s ", proc.communicate()[0])

    proc = subprocess.Popen(["net", "commit"],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, err) = proc.communicate()

    proc.wait()

    if proc.returncode != 0:
        log.info("Encountered an error applying NCLU configuration. Exiting. %s \n %s",
                 output, err)
        exit(1)

def check_version():
    '''
    Verify that we are running CL 3.7.2 or later.
    If this is a VX node, set the global VX flag to False
    '''
    global VX

    log.info("Checking Cumulus Version")
    try:
        file = open("/etc/lsb-release")
    except IOError:
        log.info("Unable to open /etc/lsb-release. Exiting")
        exit(1)

    with file:
        for line in file:
            split = line.strip().split("=")
            key = split[0]
            if key == "DISTRIB_RELEASE":
                version = split[1]
                if version.split(".")[0] < 3:
                    log.info("Hyperconverged Services only supported on Cumulus Linux"
                             "versions 3.7.2 and later. Detected CL %d.x Exiting.",
                             version.split(".")[0])
                    exit(1)

                    if version.split(".")[1] < 7:
                        log.info("Hyperconverged Services only supported on Cumulus Linux"
                                 "versions 3.7.2 and later. Detected CL 3.%d Exiting",
                                 version.split(".")[1])
                        exit(1)

                        if version.split(".")[2] < 2:
                            log.info("Hyperconverged Services only supported on Cumulus Linux"
                                     "versions 3.7.2 and later. Detected CL 3.7.%d Exiting.",
                                     version.split(".")[2])
                            exit(1)

    proc = subprocess.Popen(["decode-syseeprom"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, err) = proc.communicate()

    if proc.returncode != 0:
        log.info("Unable to read syseeprom. Exiting. %s", err)
        exit(1)

    if "VX" in output.split():
        VX = True
        log.info("Treating this as a Cumulus VX install.")


def check_required_files():
    log.info("Validating required files exist")
    try:
        open(ZTP + "/ztp_config.txt", "r")
    except IOError:
        log.info("Could not find Nutanix settings file, ztp_config.txt on the USB drive"
                 "at %s/ztp_config.txt. Exiting.", ZTP)


def main():
    '''
    Main function
    '''

    check_version()

    global ZTP

    if VX:
        ZTP = "/home/cumulus/"
    else:
        if "ZTP_USB_MOUNTPOINT" in os.environ:
            ZTP = os.environ.get("ZTP_USB_MOUNTPOINT")
            log.info("Setting ZTP mountpoint to %s", ZTP)
            check_required_files()
        else:
            log.info("Unable to determine where this ZTP script lives. Exiting")
            exit(1)

    load_config()

    if not VX:
        install_license()

    # CLAG must be enabled before NCLU commands so that the /e/n/i config is in place
    enable_clag()
    while check_nclu_ready():
        time.sleep(1)

    set_swp_mtu(get_interfaces())
    enable_mgmt_vrf()

    if UPLINKS:
        configure_uplinks()

    build_nutanix_config()
    enable_hyperconverged_service()
    apply_nclu_config()

    # NTP config must happen after NCLU is applied
    place_ntp_in_vrf()
    log.info("ZTP configuration complete!")


if __name__ == '__main__':
    main()
    exit(0)
